In [42]:
import numpy as np


def impute_missing(X: np.ndarray, strategy: str = "mean"):
    """
    Fill NaN values in each feature column using column mean or median.
    """
    if strategy == "mean":
        return mean_impute(X)
    else:
        return median_impute(X)


def median_impute(X: np.ndarray):
    """
    Fill NaN values in each feature column using column median.
    """
    filled = np.where(np.isnan(X), np.nanmedian(X, axis=0), X)
    return np.where(np.isnan(filled), 0, filled)


def mean_impute(X: np.ndarray) -> np.ndarray:
    """
    Fill NaN values in each feature column using column mean.
    """
    filled = np.where(np.isnan(X), np.mean(X, axis=0, where=~np.isnan(X)), X)
    return np.where(np.isnan(filled), 0, filled)

In [44]:
a = np.array([[1, 2, np.nan], [4, np.nan, np.nan], [np.nan, 8, np.nan]])



In [45]:
b = np.array([[1, np.nan], [3, 5]])

In [46]:
print(impute_missing(b, strategy="mean"))

[[1. 5.]
 [3. 5.]]


In [47]:
print(impute_missing(b, strategy="median"))

[[1. 5.]
 [3. 5.]]


In [48]:
print(impute_missing(a, strategy="median"))

[[1.  2.  0. ]
 [4.  5.  0. ]
 [2.5 8.  0. ]]


/tmp/ipykernel_17933/1782274750.py:18: RuntimeWarning: All-NaN slice encountered
  filled = np.where(np.isnan(X), np.nanmedian(X, axis=0), X)


In [36]:
a

array([[ 1.,  2., nan],
       [ 4., nan, nan],
       [nan,  8., nan]])